# Generated by Django 4.0.5 on 2022-06-09 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id_condominium', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id_house', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.IntegerField()),
                ('fk_condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.condominium')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id_resident', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('date_birth', models.DateTimeField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id_residence', models.AutoField(primary_key=True, serialize=False)),
                ('date_init', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('fk_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house')),
                ('fk_resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resident')),
            ],
        ),
    ]
